### ISSUE TITLE
锤子手机初始化崩溃

### ISSUE THREAD

**Issue by lynnzc** [leancloud/java-unified-sdk#35]
![image](https://user-images.githubusercontent.com/6257996/53465153-ad0fca80-3a87-11e9-8585-8218dfeae423.png)  
![32311551240212_ pic_hd](https://user-images.githubusercontent.com/6257996/53465167-bdc04080-3a87-11e9-99e9-fb5a96053266.jpg)  
getEndPoint 接口会导致崩溃

**Comment by lynnzc** [comment]
```  
Caused by: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
        at cn.leancloud.core.AppRouter.getEndpoint(AppRouter.java:181)
        at cn.leancloud.core.PaasClient.getStorageClient(PaasClient.java:68)
        at cn.leancloud.AVUser.getCurrentUser(AVUser.java:638)
        at cn.leancloud.AVUser.getCurrentUser(AVUser.java:634)
        at cn.leancloud.core.RequestPaddingInterceptor.intercept(RequestPaddingInterceptor.java:25)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall.execute(RealCall.java:92)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:12090)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
        at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
        at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by lynnzc** [comment]
stacktrace 有两处地方出错，181, 192 行都出现过

**Comment by jwfing** [comment]
@lynnzc 麻烦把 SDK 的 debug 日志贴出来看看。
