### ISSUE TITLE
LiveQuery wiki没有对应的文档

### ISSUE THREAD

**Issue by caffeine-cn** [leancloud/java-unified-sdk#55]
https://github.com/leancloud/java-unified-sdk/wiki/1.%E5%AD%98%E5%82%A8-6-LiveQuery

和官网的文档相关类对不上，需要怎么接？

**Comment by caffeine-cn** [comment]
livequery 建立也报错。。

2019-07-12 18:22:12.312 30720-30720/com.blanke.wechatbotxposed D/DirectlyOperationTube: loginLiveQuery...
2019-07-12 18:22:12.313 30720-30720/com.blanke.wechatbotxposed D/RequestCache: add request cache. client=leancloud_livequery_default_id, conv=null, request=-65535
2019-07-12 18:22:12.322 30720-30720/com.blanke.wechatbotxposed W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.leancloud.websocket.AVStandardWebSocketClient.send(cn.leancloud.command.CommandPacket)' on a null object reference
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at cn.leancloud.session.AVConnectionManager.sendPacket(AVConnectionManager.java:260)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at cn.leancloud.livequery.LiveQueryOperationDelegate.login(LiveQueryOperationDelegate.java:26)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at cn.leancloud.im.DirectlyOperationTube.loginLiveQueryDirectly(DirectlyOperationTube.java:210)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at cn.leancloud.im.DirectlyOperationTube.loginLiveQuery(DirectlyOperationTube.java:203)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at cn.leancloud.livequery.AVLiveQuery.loginLiveQuery(AVLiveQuery.java:189)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at cn.leancloud.livequery.AVLiveQuery.access$200(AVLiveQuery.java:26)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at cn.leancloud.livequery.AVLiveQuery$1.onNext(AVLiveQuery.java:161)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at cn.leancloud.livequery.AVLiveQuery$1.onNext(AVLiveQuery.java:150)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at io.reactivex.internal.operators.observable.ObservableOnErrorNext$OnErrorNextObserver.onNext(ObservableOnErrorNext.java:68)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:119)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at android.os.Looper.loop(Looper.java:164)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6893)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2019-07-12 18:22:12.323 30720-30720/com.blanke.wechatbotxposed W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:820)
2019-07-12 18:22:12.327 30720-30720/com.blanke.wechatbotxposed I/XApp: uncaught :Thread[main,5,main]
