### ISSUE TITLE
请问是从哪个版本开始放弃 android 4.x的？

### ISSUE THREAD

**Issue by JesseWo** [leancloud/java-unified-sdk#64]
```
 java.lang.NoClassDefFoundError: java.util.Objects
        at cn.leancloud.AVObject.hashCode(AVObject.java:1092)
        at java.util.HashMap.secondaryHash(HashMap.java:350)
        at java.util.HashMap.put(HashMap.java:404)
        at cn.leancloud.AVObject.hasCircleReference(AVObject.java:650)
        at cn.leancloud.AVObject.saveInBackground(AVObject.java:609)
        at cn.leancloud.AVObject.saveInBackground(AVObject.java:604)
```

**Comment by jwfing** [comment]
您好，切换到 java unified sdk 我们就开始使用 java.util.Objects 了。

**Comment by JesseWo** [comment]
> 您好，切换到 java unified sdk 我们就开始使用 java.util.Objects 了。

额，好吧。。文档中有必要提前告知一下的，要兼容Android 4的app不要迁移到这个库。
